---
repository:
  description: Ansible Role for Template
  topics: ansible, ansible-role, template
  delete_branch_on_merge: true
  has_wiki: false
#   private: false

branches:
  - name: master
    protection:
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts:
          - Lint Code Base
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
