---
name: Release to Ansible Galaxy

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  release:
    name: Release to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v1
        with:
          api_key: ${{ secrets.galaxy_api_key }}
